### ISSUE TITLE
HF models are not using key-value caching?

### ISSUE THREAD

**Issue by abhi-mosaic** [legacyai/tf-transformers#41]
I was reading the code for the [HF GPT2 benchmark](https://github.com/legacyai/tf-transformers/blob/main/benchmarks/gpt2/benchmark_hf.py), and it seems like key-value caching is not being used? This is pretty important for any kind of autoregressive generation and would greatly speed up the decoding time. HF models have had support for key-value caching for a while, see config arguments `use_cache` and `past_key_values` here: https://huggingface.co/docs/transformers/model_doc/gpt2#transformers.GPT2LMHeadModel.

I think it would be important for this project to re-benchmark the HF models with key-value caching enabled, as that is standard practice and without it the HF numbers are being handicapped.

**Comment by legacyai** [comment]
@abhi-mosaic - key- value caching has been enabled by default in HuggingFace ```.generate``` function by default. We don't have to take care of it from our end.
