### ISSUE TITLE
Colab 

### ISSUE THREAD

**Issue by Rababalkhalifa** [legacyai/tf-transformers#6]
This is great work!!! I have problem with TF2+HF with too many errors, reported to TF2, I aim to switch to tf-transformers. Though library did not work in colab, I guess there are some missing files? Thanks.

**Comment by legacyai** [comment]
Can you share the colab link, i will have a look at the problem.

**Comment by Rababalkhalifa** [comment]
Thanks. I can share the colab but there is nothing really except this:

!git clone https://github.com/legacyai/tf-transformers.git
!cd tf-transformers
#!pip install poetry
#!pip install .

**Comment by legacyai** [comment]
The reason was ``` !cd tf-transformers```, don't work as in normal machines . 
You might need to mount your google drive and stuffs. So, better options is as follows.
There was an incompatibility with ```python 3.7```. That's fixed.

Please follow these steps

```
!git clone https://github.com/legacyai/tf-transformers.git
!pip install poetry
!pip install .
````

OR

```
!pip install tf-transformers
```

Please let me know for any other issues.

**Comment by Rababalkhalifa** [comment]
Thanks, second solution worked fine.

here is a colab with the error: https://colab.research.google.com/drive/1IMM6kxQMeeKh-ZGfkENOOQVrkg6ZsZsn?usp=sharing

But it solved from my side and I will just experiment with the great functionality you providing!

**Comment by legacyai** [comment]
Thanks for pointing it out. 
Fixed. Updated the same colab.

We are on the process of changing some of the code. This is a pre-release. We might release a stable version in few days.
